# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kunde.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kunde.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bkunde.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x10KundeByIdRequest\x12\n\n\x02id\x18\x01 \x01(\r\"[\n\x05Kunde\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07vorname\x18\x02 \x01(\t\x12\x10\n\x08nachname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0cgeburtsdatum\x18\x05 \x01(\t2f\n\x10KundeReadService\x12+\n\x07\x66indAll\x12\x16.google.protobuf.Empty\x1a\x06.Kunde0\x01\x12%\n\x08\x66indById\x12\x11.KundeByIdRequest\x1a\x06.KundeB\x1a\n\x0c\x63om.swe.grpcB\nKundeProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kunde_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.swe.grpcB\nKundeProto'
  _globals['_KUNDEBYIDREQUEST']._serialized_start=44
  _globals['_KUNDEBYIDREQUEST']._serialized_end=74
  _globals['_KUNDE']._serialized_start=76
  _globals['_KUNDE']._serialized_end=167
  _globals['_KUNDEREADSERVICE']._serialized_start=169
  _globals['_KUNDEREADSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
